app/Http/routes.php
<?php

use Illuminate\Support\Facades\Input;
use App\Village;
use App\Doctor;
date_default_timezone_set("Asia/Dhaka");
Route::get('/' , function() {
	return view('auth.login');
});

Route::group(['middleware' => ['auth']] , function() {


	Route::get('/', [
    	'uses' => 'AdminController@index',
    	'as' => 'admin.index'
	]);

	//employee

	Route::get('/employee' , [
		'uses' => 'EmployeeController@getIndex',
		'as' => 'employee.index'
	]);

	Route::post('/employee/save' , [
		'uses' => 'EmployeeController@save',
		'as' => 'employee.save'
	]);

	Route::post('/employee/update' , [
		'uses' => 'EmployeeController@update',
		'as' => 'employee.update'
	]);

	Route::get('/employee/delete' , [
		'uses' => 'EmployeeController@delete',
		'as' => 'employee.delete'
	]);

	Route::get('/employee/list' , [
		'uses' => 'EmployeeController@viewList',
		'as' => 'employee.list'
	]);



	//seat

	Route::get('/seat' , [
		'uses' => 'SeatController@getIndex',
		'as' => 'seat.index'
	]);

	Route::post('/seat/save' , [
		'uses' => 'SeatController@save',
		'as' => 'seat.save'
	]);

	Route::post('/seat/update' , [
		'uses' => 'SeatController@update',
		'as' => 'seat.update'
	]);

	Route::get('/seat/delete' , [
		'uses' => 'SeatController@delete',
		'as' => 'seat.delete'
	]);

	Route::get('/seat/{seat?}/list' , [
		'uses' => 'SeatController@viewList',
		'as' => 'seat.list'
	]);

	//ReportType

	Route::get('/reportType' , [
		'uses' => 'ReportController@reportTypeIndex',
		'as' => 'reportType.index'
	]);

	Route::post('/reportType/save' , [
		'uses' => 'ReportController@reportTypesave',
		'as' => 'reportType.save'
	]);

	Route::post('/reportType/update' , [
		'uses' => 'ReportController@reportTypeupdate',
		'as' => 'reportType.update'
	]);

	Route::get('/reportType/delete' , [
		'uses' => 'ReportController@reportTypedelete',
		'as' => 'reportType.delete'
	]);

	Route::get('/reportType/list/report' , [
		'uses' => 'ReportController@reportTypeViewList',
		'as' => 'reportType.list'
	]);

	//report

	Route::resource('report','ReportController');

	Route::get('/report_view',[
    	'uses' => 'ReportController@view',
    	'as' => 'report.view'
    ]);

    Route::get('/report_get' , [
    	'uses' => 'ReportController@get',
    	'as' => 'report.get'
    ]);

	//OperationType

	Route::get('/operationType' , [
		'uses' => 'Operationcontroller@operationTypeIndex',
		'as' => 'operationType.index'
	]);

	Route::post('/operationType/save' , [
		'uses' => 'Operationcontroller@operationTypesave',
		'as' => 'operationType.save'
	]);

	Route::post('/operationType/update' , [
		'uses' => 'Operationcontroller@operationTypeupdate',
		'as' => 'operationType.update'
	]);

	Route::get('/operationType/delete' , [
		'uses' => 'Operationcontroller@operationTypedelete',
		'as' => 'operationType.delete'
	]);

	Route::get('/operationType/list/operation' , [
		'uses' => 'Operationcontroller@operationTypeViewList',
		'as' => 'operationType.list'
	]);

	//operation

	Route::resource('operation','OperationController');

	Route::get('/operation_view',[
    	'uses' => 'OperationController@view',
    	'as' => 'operation.view'
    ]);

    Route::get('/operation_get' , [
    	'uses' => 'OperationController@get',
    	'as' => 'operation.get'
    ]);

	//Patient

	Route::get('/patient' , [
		'uses' => 'PatientController@getIndex',
		'as' => 'patient.index'
	]);

	Route::post('/patient/save' , [
		'uses' => 'PatientController@save',
		'as' => 'patient.save'
	]);

	Route::post('/patient/update' , [
		'uses' => 'PatientController@update',
		'as' => 'patient.update'
	]);

	Route::get('/patient/delete' , [
		'uses' => 'PatientController@delete',
		'as' => 'patient.delete'
	]);

	Route::get('/patient/admit/list' , [
		'uses' => 'PatientController@viewList',
		'as' => 'patient.list'
	]);

    Route::get('/api/patient_search' , [
        'uses' => 'ApiController@patientSearch',
        'as' => 'apipatient.search'
    ]);

    Route::get('/api/operationtype_create' , [
        'uses' => 'ApiController@patientCreate',
        'as' => 'apipatient.create'
    ]);

    Route::get('/create_invoice', [
    	'uses' => 'InvoiceController@getIndex',
    	'as' => 'invoice.create_invoce'
    ]);

    Route::get('/invoice_view',[
    	'uses' => 'InvoiceController@view',
    	'as' => 'invoice.view'
    ]);

    Route::resource('invoice', 'InvoiceController');

    Route::resource('ecategory' , 'EmployeeCategoryController');

    Route::resource('marketing','MarketingController');

    Route::resource('specialist','SpecialistController');

    Route::resource('doctor','DoctorController');

    Route::get('/patientout_view_' , [
    	'uses' => 'DoctorController@view',
    	'as' => 'doctor.view'
    ]);

    Route::resource('village','VillageController');

    Route::resource('patientout','PatientOutController');

    Route::get('/patientout_api' , function(){
	   $doctor_id = Input::get('doctor_id');
	   $doctors = Doctor::where('id', $doctor_id)->get();
	   return Response::json($doctors); 	
	});

    Route::resource('invoiceout','InvoiceOutController');

    Route::get('/invoiceout_view',[
    	'uses' => 'InvoiceOutController@view',
    	'as' => 'invoiceout.view'
    ]);

    Route::get('/invoiceout_refund' , [
    	'uses' => 'InvoiceOutController@refund',
    	'as' => 'invoiceout.refund'
    ]);

    Route::get('/invoiceout_paid_list',[
    	'uses' => 'InvoiceOutController@paidList',
    	'as' => 'invoiceout.paidlist'
    ]);

    Route::resource('searchrf','SearchRfController');//Reference Fund : rf
    Route::get('searchrf_marketing_view', [
    	'uses' => 'SearchRFController@view',
    	'as' => 'marketing.view'
    ]);

    Route::get('/reportout_village' , function(){
	   $marketing_id = Input::get('marketing_id');
	   $villages = Village::where('marketing_id', $marketing_id)->get();
	   return Response::json($villages); 	
	});

	Route::get('daily_accounce' , [
		'uses' => 'TotalReportController@dailyAccounce' ,
		'as' => 'daily_accounce'
	]);

	Route::get('monthly_accounce' , [
		'uses' => 'TotalReportController@monthlyAccounce' ,
		'as' => 'monthly_accounce'
	]);

	Route::get('/daily_entry_hospital' , [
		'uses' => 'TotalReportController@dailyEntryHospital',
		'as' => 'daily_entry_hospital'
	]);

	Route::get('/daily_delivary_hospital' , [
		'uses' => 'TotalReportController@dailyDelivaryHospital',
		'as' => 'daily_delivary_hospital'
	]);

	Route::get('/patient_details', [
		'uses' => 'PatientController@details',
		'as' => 'patient.details'
	]);

	Route::get('/monthly_entry_hospital' , [
		'uses' => 'TotalReportController@monthlyEntryHospital',
		'as' => 'monthly_entry_hospital'
	]);

	Route::get('/monthly_delivary_hospital' , [
		'uses' => 'TotalReportController@monthlyDelivaryHospital',
		'as' => 'monthly_delivary_hospital'
	]);

	Route::get('/daily_entry_stock' , [
		'uses' => 'TotalReportController@dailyEntryStock',
		'as' => 'daily_entry_stock'
	]);

	Route::get('/daily_delivary_stock' , [
		'uses' => 'TotalReportController@dailyDelivaryStock',
		'as' => 'daily_delivary_stock'
	]);

	Route::get('/monthly_entry_stock' , [
		'uses' => 'TotalReportController@monthlyEntryStock',
		'as' => 'monthly_entry_stock'
	]);

	Route::get('/monthly_delivary_stock' , [
		'uses' => 'TotalReportController@monthlyDelivaryStock',
		'as' => 'monthly_delivary_stock'
	]);

	Route::get('/daily_entry_pharmacy' , [
		'uses' => 'TotalReportController@dailyEntrypharmacy',
		'as' => 'daily_entry_pharmacy'
	]);

	Route::get('/daily_delivary_pharmacy' , [
		'uses' => 'TotalReportController@dailyDelivarypharmacy',
		'as' => 'daily_delivary_pharmacy'
	]);

	Route::get('/monthly_entry_pharmacy' , [
		'uses' => 'TotalReportController@monthlyEntrypharmacy',
		'as' => 'monthly_entry_pharmacy'
	]);

	Route::get('/monthly_delivary_pharmacy' , [
		'uses' => 'TotalReportController@monthlyDelivarypharmacy',
		'as' => 'monthly_delivary_pharmacy'
	]);


	Route::get('/autocomplete',array('as'=>'autocomplete','uses'=>'StockController@autocomplete'));

	// Route::get('/user_registration', [
	// 	'uses' => 'RegistrationController@index',
	// 	'as' => 'user.registration'
	// ]);

	Route::resource('user','RegistrationController');
	Route::post('/password_reset' , [
		'uses' => 'RegistrationController@password_reset',
		'as' => 'password_reset'
	]);

	Route::resource('refund' , 'RefundController');

	Route::resource('stock' , 'StockController');

	Route::post('stock_process' , [
		'uses' => 'StockController@process',
		'as' => 'stock.process'
	]);

	Route::resource('accounce_cost' , 'AccounceController');

	Route::get('/autocomplete_doctor',array('as'=>'autocomplete_doctor','uses'=>'PatientOutController@autocomplete_doctor'));

	Route::get('/autocomplete_village',array('as'=>'autocomplete_village','uses'=>'InvoiceOutController@autocomplete_village'));

	Route::get('/autocomplete_marketing',array('as'=>'autocomplete_marketing','uses'=>'SearchRFController@autocomplete_marketing'));

	Route::get('/autocomplete_indoor_patient',array('as'=>'autocomplete_indoor_patient','uses'=>'ReportController@autocomplete_indoor_patient'));
	
});


Route::auth();

Route::get('/home', 'HomeController@index');

resources/views/admin/accounce_cost.blade.php
 @extends('layouts.master')

@section('top_header')
  Accounce Cost Information
@endsection


@section('content')

<!-- main area -->
<div class="main-content">

  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
          Add New Cost
        </div>
        <form action="{{ route('accounce_cost.store')}}" method="POST">
        {{ csrf_field() }}
        <div class="panel-body">
        @if(Session::has('success'))
        <div class="alert alert-success">
          {{Session::get('success')}}
        </div>
       @endif
          <div class="form-group clear">
            <label class="col-sm-2 control-label">Particular</label>
            <div class="col-sm-7">
              <input type="text" class="form-control" name="name" required>
            </div>
          </div>
          <div class="form-group clear">
            <label class="col-sm-2 control-label">Taka</label>
            <div class="col-sm-7">
              <input type="number" class="form-control" name="taka" required>
            </div>
          </div>

        </div>
        <div class="panel-footer" style="overflow: hidden;">
          <button type="submit" class="btn btn-success pull-right">Save</button>
        </div>
        </form>
    </div>
  </div>

  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
         View ALL Accounce Cost
        </div>
        <div class="panel-body">
        @if(Session::has('success'))
        <div class="alert alert-success">
          {{Session::get('success')}}
        </div>
      @endif
        
        <div class="table-responsive">
        <table class="table table-bordered table-striped mb0">
          <thead>
            <tr>
              <th>No.</th>
              <th>Particular</th>
              <th>Taka</th>
            </tr>
          </thead>
          @php 
            $totalAccounce = 0
          @endphp
          <tbody>
            <?php $i =1 ; ?>
            @foreach ($accounce_costs as $accounce_cost)
              <tr>
              <td><?php echo $i; ?></td>
              <td>{{ $accounce_cost->name }}</td>
              <td>{{ $accounce_cost->taka }} /-</td> 
                  @php 
                  $totalAccounce = $accounce_cost->taka+ $totalAccounce @endphp                         
            </tr>
            <?php $i++; ?>
            @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th></th>
              <th>Total</th>
              <th>{{ $totalAccounce }} Tk.</th>
            </tr>
          </tfoot>
        </table>
        <section>
      </section>
      </div>

      </div>
    </div>
  </div>
  <!-- /main area -->
</div>
<!-- /content panel -->
@endsection

resources/views/admin/daily_entry_pharmacy.blade.php
@extends('layouts.master')

@section('top_header')
  Daily Entry information
@endsection


@section('content')

<!-- main area -->
<div class="main-content">
  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
          Daily Entry Information
        </div>
        <div class="panel-body">
        <div class="table-responsive">
        <table class="table table-bordered table-striped mb0">
          <thead>
            <tr>
              <th>No.</th>
              <th>Company Name</th>
              <th>Medicine Name</th>
              <th>Piece</th>
              <th>Price</th>
              <th>Subtotal</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>No.</th>
              <th>Company Name</th>
              <th>Medicine Name</th>
              <th>Piece</th>
              <th>Price</th>
              <th>Subtotal</th>
            </tr>         
            </tfoot>
          <tbody>
            <tr>
              <td>01</td>         
              <td>Square</td>         
              <td>Neoceptin R</td>         
              <td>500</td>
              <td>2 Tk.</td>
              <td>1000 Tk.</td>                 
            </tr>
            <tr>
              <td>01</td>         
              <td>Square</td>         
              <td>Neoceptin R</td>         
              <td>500</td>
              <td>2 Tk.</td>
              <td>1000 Tk.</td>                 
            </tr><tr>
              <td>01</td>         
              <td>Square</td>         
              <td>Neoceptin R</td>         
              <td>500</td>
              <td>2 Tk.</td>
              <td>1000 Tk.</td>                 
            </tr><tr>
              <td>01</td>         
              <td>Square</td>         
              <td>Neoceptin R</td>         
              <td>500</td>
              <td>2 Tk.</td>
              <td>1000 Tk.</td>                 
            </tr><tr>
              <td>01</td>         
              <td>Square</td>         
              <td>Neoceptin R</td>         
              <td>500</td>
              <td>2 Tk.</td>
              <td>1000 Tk.</td>                 
            </tr>
            <tr>
              <td></td>         
              <td></td>         
              <td></td>         
              <td></td>
              <td></td>
              <td>2,75,000 Tk.</td>                 
            </tr>
          </tbody>
        </table>
      </div>

      </div>
    </div>
  </div>
  <!--Admit Patient Section End-->

  <!-- /main area -->
</div>
<!-- /content panel -->
@endsection

resources/views/admin/invoiceout_paid_list.blade.php
@extends('layouts.master')

@section('top_header')
  View All Paid Report
@endsection


@section('content')

<!-- main area -->
<div class="main-content">
  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
          View All PAID Report List
        </div>
        <div class="panel-body">
        @if(Session::has('success'))
        <div class="alert alert-success">
          {{Session::get('success')}}
        </div>
      @endif
        
        <div class="table-responsive">
        <table class="table table-bordered table-striped mb0">
          <thead>
            <tr>
              <th>No.</th>
              <th>Report ID</th>
              <th>P. ID</th>
              <th>View</th>
              @if(Auth::user()->super_id == 1)
              <th>Delete</th>
              @endif
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>No.</th>
              <th>Report ID</th>
              <th>P. ID</th>
              <th>View</th>
              @if(Auth::user()->super_id == 1)
              <th>Delete</th>
              @endif
            </tr>
          </tfoot>
          <tbody>
            <?php $i =1 ; ?>
            @foreach ($invoiceouts as $invoiceout)
              <tr>
              <td><?php echo $i; ?></td>
              <td>{{ $invoiceout->id}}</td>
              <td>{{ $invoiceout->patient_id }}-{{ $invoiceout->created_at->format('m-d-Y')}}</td>
              <td>
                <form action="{{ route('invoiceout.view') }}" method="GET">
                  {{ csrf_field() }}
                <input name="_method" type="hidden" value="GET">
                <input type="hidden" name="invoiceout_id" value="{{ $invoiceout->id }}">
                <button class="btn btn-primary">Print</button>
                </form>
              </td>
              
              @if(Auth::user()->super_id == 1)
              <td><a data-toggle="modal" data-target="#delete<?php echo $i; ?>" href=""><button type="button" class="btn btn-danger">Delete</button></a></td>
              @endif
              <div class="modal" id="delete<?php echo $i; ?>" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Delete Report's Information</h4>
                  </div>
                  <div class="modal-body">
                      Are you sure ?
                  </div>
                  <form action="{{ route('invoiceout.destroy' , $invoiceout->id)}}" method="POST">
                  <input name="_method" type="hidden" value="DELETE">
                  {{ csrf_field() }}

                  <div class="modal-footer no-border">
                      <button type="button" class="btn btn-info" data-dismiss="modal">No</button>
                      <button type="submit" class="btn btn-primary">Yes</button>
                  </div>
                  </form>
                </div>
              </div>
              </div>
            </tr>
            <?php $i++; ?>
            @endforeach
          </tbody>
        </table>
        <section>
        <nav>
          <ul class="pager">
              @if($invoiceouts->currentPage() !== 1)
                <li class="previous"><a href="{{ $invoiceouts->previousPageUrl() }}"><span aria-hidden="true">&larr;</span> Older</a></li>
              @endif
              @if($invoiceouts->currentPage() !== $invoiceouts->lastPage() && $invoiceouts->hasPages())
                <li class="next"><a href="{{ $invoiceouts->nextPageUrl() }}">Newer <span aria-hidden="true">&rarr;</span></a></li>
              @endif
          </ul>
        </nav>
      </section>
      </div>

      </div>
    </div>
  </div>
  <!-- /main area -->
</div>
<!-- /content panel -->
@endsection


@section('run_custom_jquery')

@endsection

resources/views/admin/refund_list.blade.php
@extends('layouts.master')

@section('top_header')
  View All Report
@endsection


@section('content')

<!-- main area -->
<div class="main-content">
  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
          View All Refund List
        </div>
        <div class="panel-body">
        @if(Session::has('success'))
        <div class="alert alert-success">
          {{Session::get('success')}}
        </div>
      @endif
        
        <div class="table-responsive">
        <table class="table table-bordered table-striped mb0">
          <thead>
            <tr>
              <th>No.</th>
              <th>Report ID</th>
              <th>Patient ID</th>
              <th>View</th>
              @if(Auth::user()->super_id == 1)
              <th>Delete</th>
              @endif
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>No.</th>
              <th>Report ID</th>
              <th>Patient ID</th>
              <th>View</th>
              @if(Auth::user()->super_id == 1)
              <th>Delete</th>
              @endif
            </tr>
          </tfoot>
          <tbody>
            <?php $i =1 ; ?>
            @foreach ($refunds as $refund)
              <tr>
              <td><?php echo $i; ?></td>
              <td>{{ $refund->invoice_out_id}}</td>
              <td>{{ $refund->invoiceOut->patient_id}}-{{$refund->invoiceOut->created_at->format('m-d-Y')}}</td>
              @if(Auth::user()->super_id == 1)
              <td>
                <form action="{{ route('refund.create') }}" method="GET">
                  {{ csrf_field() }}
                <input name="_method" type="hidden" value="GET">
                <input type="hidden" name="refund_id" value="{{ $refund->id }}">
                <button class="btn btn-primary">Print</button>
                </form>
              </td>

              <td><a data-toggle="modal" data-target="#delete<?php echo $i; ?>" href=""><button type="button" class="btn btn-danger">Delete</button></a></td>
              @endif
              <div class="modal" id="delete<?php echo $i; ?>" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Delete Refund Report's </h4>
                  </div>
                  <div class="modal-body">
                      Are you sure ?
                  </div>
                  <form action="{{ route('refund.destroy' , $refund->id)}}" method="POST">
                  <input name="_method" type="hidden" value="DELETE">
                  <input type="hidden" name="report_id" value="{{ $refund->report_id }}">
                  <input type="hidden" name="refund_id" value="{{ $refund->id }}">
                  {{ csrf_field() }}

                  <div class="modal-footer no-border">
                      <button type="button" class="btn btn-info" data-dismiss="modal">No</button>
                      <button type="submit" class="btn btn-primary">Yes</button>
                  </div>
                  </form>
                </div>
              </div>
              </div>
            </tr>
            <?php $i++; ?>
            @endforeach
          </tbody>
        </table>
        <section>
        <nav>
          <ul class="pager">
              @if($refunds->currentPage() !== 1)
                <li class="previous"><a href="{{ $refunds->previousPageUrl() }}"><span aria-hidden="true">&larr;</span> Older</a></li>
              @endif
              @if($refunds->currentPage() !== $refunds->lastPage() && $refunds->hasPages())
                <li class="next"><a href="{{ $refunds->nextPageUrl() }}">Newer <span aria-hidden="true">&rarr;</span></a></li>
              @endif
          </ul>
        </nav>
      </section>
      </div>

      </div>
    </div>
  </div>
  <!-- /main area -->
</div>
<!-- /content panel -->
@endsection


@section('run_custom_jquery')

@endsection

resources/views/admin/specialist.blade.php
@extends('layouts.master')

@section('top_header')
  Specialist Category
@endsection


@section('content')

<!-- main area -->
<div class="main-content">

  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
          Add New Name
        </div>
        <form action="{{ route('specialist.store')}}" method="POST">
        {{ csrf_field() }}
        <div class="panel-body">
        @if(Session::has('success1'))
        <div class="alert alert-success">
          {{Session::get('success1')}}
        </div>
       @endif
          <div class="form-group">
              <label class="col-sm-2 control-label">Name</label>
              <div class="col-sm-7">
                <input type="text" class="form-control" name="name" required>
              </div>
            </div>
        </div>
        <div class="panel-footer" style="overflow: hidden;">
          <button type="submit" class="btn btn-success pull-right">Save</button>
        </div>
        </form>
    </div>
  </div>

  <div class="row">
    <div class="panel mb25">
        <div class="panel-heading border">
         View ALL Specialist Category
        </div>
        <div class="panel-body">
        @if(Session::has('success'))
        <div class="alert alert-success">
          {{Session::get('success')}}
        </div>
      @endif
        
        <div class="table-responsive">
        <table class="table table-bordered table-striped mb0">
          <thead>
            <tr>
              <th>No.</th>
              <th>Name</th>
              <th>Edit</th>
              @if(Auth::user()->super_id == 1)
              <th>Delete</th>
              @endif
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>No.</th>
              <th>Name</th>
              <th>Edit</th>
              @if(Auth::user()->super_id == 1)
              <th>Delete</th>
              @endif
            </tr>
          </tfoot>
          <tbody>
            <?php $i =1 ; ?>
            @foreach ($specialists as $specialist)
              <tr>
              <td><?php echo $i; ?></td>
              <td>{{ $specialist->name }}</td>

              <td><a data-toggle="modal" data-target="#edit<?php echo $i; ?>" href=""><button type="button" class="btn btn-info">Edit</button></a></td>

              <div class="modal" id="edit<?php echo $i; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                      <h4 class="modal-title">Edit Information</h4>
                    </div>
                    <div class="modal-body">
                      <div class="row mb25">
              <form class="form-horizontal bordered-group" role="form" action="{{ route('specialist.update' , $specialist->id)}}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <input name="_method" type="hidden" value="PUT">

          
            <div class="form-group clear">
              <label class="col-sm-3 control-label">Name</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" name="name" value="{{ Request::old('name') ? Request::old('name') : isset($specialist) ? $specialist->name : '' }} " required>
              </div>
            </div>

              </div>
              </div>
              <div class="modal-footer no-border">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success">Update</button>
              </div>
            </div>
          </div>
        </div>
         </form>
              
              @if(Auth::user()->super_id == 1)
              <td><a data-toggle="modal" data-target="#delete<?php echo $i; ?>" href=""><button type="button" class="btn btn-danger">Delete</button></a></td>
              @endif
              <div class="modal" id="delete<?php echo $i; ?>" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Delete Specialist Category</h4>
                  </div>
                  <div class="modal-body">
                      Are you sure ?
                  </div>
                    <form action="{{ route('specialist.destroy' , $specialist->id)}}" method="POST">
                    {{ csrf_field() }}
                  <input name="_method" type="hidden" value="DELETE">
                  <div class="modal-footer no-border">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                  </div>
                  </form>
                </div>
              </div>
              </div>
            </tr>
            <?php $i++; ?>
            @endforeach
          </tbody>
        </table>
        <section>
        <nav>
          <ul class="pager">
              @if($specialists->currentPage() !== 1)
                <li class="previous"><a href="{{ $specialists->previousPageUrl() }}"><span aria-hidden="true">&larr;</span> Older</a></li>
              @endif
              @if($specialists->currentPage() !== $specialists->lastPage() && $specialists->hasPages())
                <li class="next"><a href="{{ $specialists->nextPageUrl() }}">Newer <span aria-hidden="true">&rarr;</span></a></li>
              @endif
          </ul>
        </nav>
      </section>
      </div>

      </div>
    </div>
  </div>
  <!-- /main area -->
</div>
<!-- /content panel -->
@endsection